language: csharp
solution: RoutePlanner.WebClient.sln
dotnet: 1.1
services:
  - docker
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-1-003177
      mono: none
      env: DOTNETCORE=1
