version: '2'

services:
  routeplanner.webclient:
    image: routeplanner.webclient:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "5000:5000"
    environment:
      - REMOTE_DEBUGGING
